// <auto-generated />
using System;
using DrugInfo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrugInfo.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("DrugInfo.Api.Entities.Drug", b =>
                {
                    b.Property<int>("DrugId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ApprovalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DosageForm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DrugId");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("DrugInfo.Api.Entities.DrugIngredient", b =>
                {
                    b.Property<int>("DrugId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DrugId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("DrugIngredients");
                });

            modelBuilder.Entity("DrugInfo.Api.Entities.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pharmacology")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("DrugInfo.Api.Entities.DrugIngredient", b =>
                {
                    b.HasOne("DrugInfo.Api.Entities.Drug", "Drug")
                        .WithMany("DrugIngredients")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrugInfo.Api.Entities.Ingredient", "Ingredient")
                        .WithMany("DrugIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("DrugInfo.Api.Entities.Drug", b =>
                {
                    b.Navigation("DrugIngredients");
                });

            modelBuilder.Entity("DrugInfo.Api.Entities.Ingredient", b =>
                {
                    b.Navigation("DrugIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
